/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.*;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Equipe Forca
 */
public class VGame extends javax.swing.JFrame {
    //CController cC = new CController();
    

    /**
     * Creates new form Jogo
     */
    public VGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        LbSetStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LbSize = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LbDica = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InChar = new javax.swing.JTextField();
        OuWord = new javax.swing.JTextField();
        OuChar = new javax.swing.JTextField();
        OuPoints = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        OuName = new javax.swing.JLabel();
        OuLevel = new javax.swing.JLabel();
        BtnExit = new javax.swing.JButton();
        BtnContinue = new javax.swing.JButton();
        LbLife1 = new javax.swing.JLabel();
        LbLife2 = new javax.swing.JLabel();
        LbLife3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FORCA");
        setBackground(new java.awt.Color(127, 214, 196));
        setForeground(new java.awt.Color(158, 212, 209));
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(162, 226, 240));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 46, 137));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("JOGO DA FORCA");

        LbSetStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/vazia.png"))); // NOI18N
        LbSetStatus.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jLabel2.setText("Com");

        LbSize.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jLabel3.setText("letras, a dica é:");

        LbDica.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        LbDica.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LbDica.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        jLabel4.setText("Entre com uma letra:");

        InChar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InCharKeyReleased(evt);
            }
        });

        OuWord.setEditable(false);
        OuWord.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        OuChar.setEditable(false);
        OuChar.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N

        OuPoints.setBackground(new java.awt.Color(255, 255, 255));
        OuPoints.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        OuPoints.setForeground(new java.awt.Color(0, 46, 137));
        OuPoints.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jPanel2.setForeground(new java.awt.Color(0, 46, 137));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        OuName.setBackground(new java.awt.Color(255, 255, 255));
        OuName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        OuName.setForeground(new java.awt.Color(0, 46, 137));
        OuName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        OuLevel.setBackground(new java.awt.Color(255, 255, 255));
        OuLevel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        OuLevel.setForeground(new java.awt.Color(0, 46, 137));
        OuLevel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        BtnExit.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        BtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exit.png"))); // NOI18N
        BtnExit.setText("SAIR");
        BtnExit.setBorder(new javax.swing.border.SoftBevelBorder(0));
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });

        BtnContinue.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        BtnContinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/next.png"))); // NOI18N
        BtnContinue.setText("CONTINUAR");
        BtnContinue.setBorder(new javax.swing.border.SoftBevelBorder(0));
        BtnContinue.setEnabled(false);
        BtnContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnContinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(OuPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OuName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbSetStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LbLife1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LbLife2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LbLife3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(OuChar)
                            .addComponent(OuWord)
                            .addComponent(LbDica, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(OuLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InChar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(BtnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(OuName, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OuPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OuLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LbSetStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LbSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LbDica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(InChar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OuWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(OuChar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbLife1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbLife2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbLife3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(238, 238, 238)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InCharKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InCharKeyReleased
        //CController cC = new CController();
        CController cC = ObjectManager.getInstance();
        String l = cC.Valida(InChar.getText());
        InChar.setText(l);
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cC.addCharacter();
        }
    }//GEN-LAST:event_InCharKeyReleased

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        CController cC = ObjectManager.getInstance();
        cC.Exit();
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnContinueActionPerformed
        CController cC = ObjectManager.getInstance();
        cC.Initializes();
    }//GEN-LAST:event_BtnContinueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VGame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnContinue;
    private javax.swing.JButton BtnExit;
    private javax.swing.JTextField InChar;
    private javax.swing.JLabel LbDica;
    private javax.swing.JLabel LbLife1;
    private javax.swing.JLabel LbLife2;
    private javax.swing.JLabel LbLife3;
    private javax.swing.JLabel LbSetStatus;
    private javax.swing.JLabel LbSize;
    private javax.swing.JTextField OuChar;
    public javax.swing.JLabel OuLevel;
    public javax.swing.JLabel OuName;
    public javax.swing.JLabel OuPoints;
    private javax.swing.JTextField OuWord;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    public void DefineInitial(String Name, int Size, String Description, String Output, String ListTyped, String Level, int Points, int Life){
        OuName.setText(Name);
        OuWord.setText(Output);
        OuPoints.setText(String.valueOf(Points));
        OuLevel.setText(Level);
        OuChar.setText(ListTyped);
        LbSize.setText(String.valueOf(Size));
        LbDica.setText(String.valueOf(Description));
        
        Life(Life);
        
        InChar.setText("");
        InChar.setEditable(true);
        InChar.setEnabled(true);
        BtnContinue.setEnabled(false);
        
        //ImageIcon img = new ImageIcon(this.getClass().getResource("/Image/Vazia.png"));
        ImageIcon img = new ImageIcon(this.getClass().getResource("/Image/vazia.png"));
        LbSetStatus.setIcon(img);
    }
    
    public void DefineGame(String OutputWord, String OutputCharacteres, String Image, int Life){
        InChar.setText("");
        OuWord.setText(OutputWord);
        OuChar.setText(OutputCharacteres);
        Life(Life);
        ImageIcon img = new ImageIcon(this.getClass().getResource(Image));
        LbSetStatus.setIcon(img);
    }
    
    public void Victory(String FinalWord, int GetPoints, String Level){
        InChar.setText("");
        InChar.setEditable((false));
        InChar.setEnabled(false);
        OuPoints.setText(String.valueOf(GetPoints));
        OuWord.setText(FinalWord);
        OuLevel.setText(Level);
        OuChar.setText("Você ganhou! Parabéns");
        BtnContinue.setEnabled(true);
        ImageIcon img = new ImageIcon(this.getClass().getResource("/Image/victory.png"));
        LbSetStatus.setIcon(img);
    }
    
    public void GameOver(int Life){
        InChar.setText("");
        InChar.setEditable(false);
        InChar.setEnabled(false);
        BtnContinue.setEnabled(true);
        ImageIcon img = new ImageIcon(this.getClass().getResource("/Image/gameover.png"));
        LbSetStatus.setIcon(img);
        Life(Life);
    }
    
    public void FinalizeGame(int Points, String PlayerName, int Life, String Status, String Message, String Icon){
        InChar.setText("");
        InChar.setEditable(false);
        InChar.setEnabled(false);
        OuName.setText(PlayerName);
        OuLevel.setText("Game Over");
        OuPoints.setText(String.valueOf(Points));
        Life(Life);
        OuWord.setText(Status);
        OuChar.setText(Message);
        ImageIcon img = new ImageIcon(this.getClass().getResource(Icon));
        LbSetStatus.setIcon(img);
        
        BtnContinue.setEnabled(true);
    }
    
    public void Life(int Life){
        ImageIcon LifeIcon = new ImageIcon(this.getClass().getResource("/Image/life.png"));
        ImageIcon DeathIcon = new ImageIcon(this.getClass().getResource("/Image/death.png"));
        if(Life == 3){
            LbLife1.setIcon(LifeIcon);
            LbLife2.setIcon(LifeIcon);
            LbLife3.setIcon(LifeIcon);
        }
        if(Life == 2){
            LbLife1.setIcon(LifeIcon);
            LbLife2.setIcon(LifeIcon);
            LbLife3.setIcon(DeathIcon);
        }
        if(Life == 1){
            LbLife1.setIcon(LifeIcon);
            LbLife2.setIcon(DeathIcon);
            LbLife3.setIcon(DeathIcon);
        }
        if(Life == 0){
            LbLife1.setIcon(DeathIcon);
            LbLife2.setIcon(DeathIcon);
            LbLife3.setIcon(DeathIcon);
        }
    }
}

